apiVersion: batch/v1
kind: Job
metadata:
  name: pi2
spec:
  parallelism: 2
  completions: 4
  template:
    metadata:
      name: pi2
    spec:
      containers:
      - name: pi2
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
