apiVersion: batch/v1
kind: Job
metadata:
  name: pi3
spec:
  activeDeadlineSeconds: 1
  template:
    metadata:
      name: pi3
    spec:
      containers:
      - name: pi3
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
