apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    another: value
spec:
  containers:
  - name: master
    image: mongo:3
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
    ports:
    - containerPort: 27017
