apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mongo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: master
        image: mongo:3
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 27017
