kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tomcat-pvc-1
  labels:
    app: tomcat
    storage: tomcat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

