apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-storage
  labels:
    storage: apache
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 149.44.139.188
    path: "/share"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apache-storage
  labels:
    storage: apache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
