kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apache-pvc-1
  labels:
    app: apache
    storage: apache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

